#/usr/bin/sh

go get	"github.com/jaytaylor/html2text"
go get	"github.com/edwindvinas/percent"
go get	"github.com/edwindvinas/jsonq"
go get	"gopkg.in/zabawaba99/firego.v1"
go get	"github.com/dustin/go-humanize"
go get	"github.com/edwindvinas/html"
go get	"google.golang.org/api/googleapi/transport"
go get	"google.golang.org/api/plus/v1"
go get	"google.golang.org/api/youtube/v3"
go get	"golang.org/x/net/context"
go get	"google.golang.org/appengine"
go get	"golang.org/x/oauth2/google"
go get	"github.com/dgrijalva/jwt-go"
go get	"github.com/PuerkitoBio/goquery"
go get	"gopkg.in/neurosnap/sentences.v1/english"
go get	"golang.org/x/oauth2"
go get	"github.com/google/go-github/github"
go get	"github.com/blevesearch/bleve"
go get	"github.com/edwindvinas/sillyname-go"
go get "github.com/edwindvinas/user_agent"
go get "github.com/olekukonko/tablewriter"